### ISSUE TITLE
Hardcoded folders

### ISSUE THREAD

**Issue by sanderbreur** [modexp/daqana#10]
In the daqprocessor_single_calibrate we have hard coded the modulation_basedir and the run dir. These are institute dependent. 

To solve this we could:
1. Use placeholders in the general github code, explain that the user has to hardcode them in themselves in the installation documentation and put a print statement with that info in the code or
2. Make an ini file per institute where we keep the institute dependent hard coded options. Only the institute then has to be hard coded in the daqprocessor file.

InDir and outDir should always be options in our shared Github code.

(these are small change, but will make new installation a bit easier)

**Comment by pbarrow** [comment]
I think first we need to consolidate the analysis files and daqana into one package. From there the directories to the analysis files are then known. We are having issues processing as a result of bugs in the analysis and calibration files.

I also feel as though there should be no hardcoded folders at all. If we want, we can discuss this further, but it would be good if we force the filesystem to be the same wrt where the processing code is. This way people will not need to individually fill out the directories.

I think it's time to consolidate each individual python processor into one file. We can add additional options if we want to accommodate this, but there are too many processor files right now.

**Comment by sanderbreur** [comment]
Peter, I agree on all accounts :)

Op di 19 apr. 2016 om 11:22 schreef pbarrow notifications@github.com:

**Comment by adambrown1** [comment]
Fixed by pull request #12
