### ISSUE TITLE
Calibration files not found after processing

### ISSUE THREAD

**Issue by cassie-fletcher** [modexp/daqana#5]
Once the file is done processing, the processor cannot find some calibration files.  Perhaps I don't have my directories set up correctly?  

The directory structure is as follows: 

> modulation_basedir = "/home/reuterc/Documents/"
> # output_basedir to be set to directory where the output structure should be
> 
> output_basedir = "/project/darkmatters/modulation/p_Changing_Voltage"
> # run dir: where do you want all the scipts to live?
> 
> run_dir = modulation_basedir + "/processing_scripts"

Attached is a pdf of the all the daqana messages

[screendump.pdf](https://github.com/modexp/daqana/files/38182/screendump.pdf)

**Comment by acolijn** [comment]
Hi Cassie,

Can you please localise the following files: ecal.h and ecal.C

AP

**Comment by acolijn** [comment]
and please send me: do_analyzer_mx_p_20151111_2131.C

AP

**Comment by sanderbreur** [comment]
Hey AP, do you have a fix for this issue? (we need to run the same processor at all institutes now that we want to make the same plots for the paper)

**Comment by pbarrow** [comment]
We really really need a fix for this. The code doesn't even work with <8 detectors running.

**Comment by acolijn** [comment]
Hi Peter
Will fix on Monday. Are you available for tests & questions?
AP

**Comment by pbarrow** [comment]
great! I'll be available all week for any tests, or answers you may need!

**Comment by acolijn** [comment]
Hi Peter,

Few question before stating debug session:
1. If you run the system with 8 detectors, do you have any problems with the processing code? (even a run without the detectors actually ON, but included in the DAQ would be helpful)
2. Can you maybe send me (Dropbox?) the data from a short run with (i) all detectors ON and in DAQ (ii) a few detectors ON and in DAQ (iii) a few detectors in DAQ only

AP

**Comment by pbarrow** [comment]
Hi AP,
1. A dataset with 8 detectors running has no problem in being processed currently. Only issue I had is that, for some reason, I had to add the full path to the MC_(source)_modulation.root files in the analyzer.C code. (lines 132-141)
2. I have datasets now for cases (i) and (ii). Will collect (iii) today. What drop box can I send them to?

Peter

**Comment by adambrown1** [comment]
I believe this is now fine, I have been processing data with 7 detectors with no problem and the calibrated data directory problem does not seem to be present.
