### ISSUE TITLE
./daqprocessor.py fails because parsArguments was deleted

### ISSUE THREAD

**Issue by sanderbreur** [modexp/daqana#8]
Right now ./daqprocessor.py will fail with the following error:
  File "./daqprocessor.py", line 18, in <module>
    filebase, outdir, grafOn, longRoot, slowOn, calibration = parseArguments(sys.argv[1:])
NameError: name 'parseArguments' is not defined

This was caused by @pbarrow 's commit 37eae2a33573c40c2695b2c4168c817ff07f9f73 in which a new (and better) method was introduced. The commit deleted the parseArguments while not changing daqprocessor.py but introducing a new daqprocessor_single_calibrate.py file

The solution is probably to check if the new 'daqprocessor_single_calibrate.py' file does everything 'daqprocessor.py' did and if so put the new code in 'daqprocessor.py' and delete 'daqprocessor_single_calibrate.py'.

**Comment by pbarrow** [comment]
My apologies if the code is not working. I was under the impression that daqprocessor_single_calibrate.py was the current working version of the code. I therefore have not changed the daqprocessor.py code to account for the changes in processorlib.py.

The fix, however, should be simple. Since I am only editing the arguments, it should be possible to replace the appropriate lines. 

I will write a new commit for this, in the meantime. You can import argparse at the top of daqprocessor.py and simply copy and paste lines 42-62 in daqprocessor_single_calibrate.py in replacement of line 18 in daqprocessor.py

**Comment by acolijn** [comment]
Sorry sander 

I found the same and with very minor mods the code runs. Will put the new (better) way of running the code of Peter in the documentation.  Will show you tomorrow how to run. 

AP

**Comment by sanderbreur** [comment]
No problem, I am just trying to clean stuff up a bit.

And we can change the 'current working version', but I want to be sure that
the installation information on the wiki is correct:
http://www.physics.purdue.edu/darkmatters/doku.php?id=modulation:daq:daqana

And if we change the main file then the make file should also be adjusted
accordingly :)

Op wo 16 mrt. 2016 om 16:24 schreef Auke Colijn notifications@github.com:

> Sorry sander
> 
> I found the same and with very minor mods the code runs. Will put the new
> (better) way of running the code of Peter in the documentation. Will show
> you tomorrow how to run.
> 
> AP
> 
> Sent from my iPad
>

**Comment by cassie-fletcher** [comment]
I believe Auke's the last one who modified the daqana page on the wiki.  So
the information on the wiki should be correct for the current working
version, since Auke posted the last working version, if I'm not mistaken :)

**Comment by acolijn** [comment]
> On 16 mrt. 2016, at 18:42, Cassie notifications@github.com wrote:
> 
> I believe Auke's the last one who modified the daqana page on the wiki. So
> the information on the wiki should be correct for the current working
> version, since Auke posted the last working version, if I'm not mistaken :)

These were changes made by Peter: much simpler now to add new arguments to the python scripts. Will take care of docs later. 

AP 

> On Wed, Mar 16, 2016 at 12:04 PM, Sander Breur notifications@github.com
> wrote:
> 
> > No problem, I am just trying to clean stuff up a bit.
> > 
> > And we can change the 'current working version', but I want to be sure that
> > the installation information on the wiki is correct:
> > http://www.physics.purdue.edu/darkmatters/doku.php?id=modulation:daq:daqana
> > 
> > And if we change the main file then the make file should also be adjusted
> > accordingly :)
> > 
> > Op wo 16 mrt. 2016 om 16:24 schreef Auke Colijn <notifications@github.com
> > 
> > > :
> > > 
> > > Sorry sander
> > > 
> > > I found the same and with very minor mods the code runs. Will put the new
> > > (better) way of running the code of Peter in the documentation. Will show
> > > you tomorrow how to run.
> > > 
> > > AP
> > > 
> > > Sent from my iPad
> > >

**Comment by cassie-fletcher** [comment]
Cool, thanks :)

**Comment by adambrown1** [comment]
Fixed by pull request #12
